### ISSUE TITLE
Database name is ignored and a database named eventuate is required

### ISSUE THREAD

**Issue by amirh715** [eventuate-tram/eventuate-tram-core#176]
I've set everything up but it seems that `spring.datasource.url` is ignored by Eventuate Tram and it expects a database named `eventuate` regardless. What am I doing wrong?
This is the application.yml:
```
server:
  port: 8081
spring:
  application:
    name: oneaccess
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/MyDatabaseName
    username: root
    password: Tempo123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: secret
  expire-in-days: 30
eventuatelocal:
  kafka:
    bootstrap:
      servers: http://localhost:9092
  zookeeper:
    connection:
      string: http://localhost:2181
```
