### ISSUE TITLE
NullPointerException when setting eventuate.outbox.id

### ISSUE THREAD

**Issue by amirh715** [eventuate-tram/eventuate-tram-core#177]
I'm trying to use Eventuate Tram and Eventuate CDC with Apache Kafka. Everything works fine until I set `eventuate.outbox.id = 1` on my `application.yml` file. I need to have multiple readers/pipelines. I've searched a lot but could not find any answers.
The details are included below:

**Stack trace**
```
java.lang.NullPointerException
	at io.eventuate.common.spring.jdbc.EventuateSpringJdbcStatementExecutor.insertAndReturnGeneratedId(EventuateSpringJdbcStatementExecutor.java:38)
	at io.eventuate.common.jdbc.EventuateCommonJdbcOperations.insertIntoMessageTableDatabaseId(EventuateCommonJdbcOperations.java:163)
	at io.eventuate.common.jdbc.EventuateCommonJdbcOperations.insertIntoMessageTable(EventuateCommonJdbcOperations.java:126)
	at io.eventuate.common.jdbc.EventuateCommonJdbcOperations.insertIntoMessageTable(EventuateCommonJdbcOperations.java:106)
	at io.eventuate.tram.messaging.producer.jdbc.MessageProducerJdbcImpl.send(MessageProducerJdbcImpl.java:28)
	at io.eventuate.tram.messaging.producer.common.MessageProducerImpl.send(MessageProducerImpl.java:49)
	at io.eventuate.tram.messaging.producer.common.MessageProducerImpl.lambda$send$2(MessageProducerImpl.java:37)
	at io.eventuate.tram.messaging.producer.common.MessageProducerImplementation.withContext(MessageProducerImplementation.java:14)
	at io.eventuate.tram.messaging.producer.common.MessageProducerImpl.send(MessageProducerImpl.java:37)
	at io.eventuate.tram.events.publisher.DomainEventPublisherImpl.publish(DomainEventPublisherImpl.java:35)
	at io.eventuate.tram.events.publisher.DomainEventPublisherImpl.publish(DomainEventPublisherImpl.java:25)
	at com.easybuy.oneaccess.domain.services.UserCommandService.registerNewUser(UserCommandService.java:40)
```
**application.yml**
```
eventuate:
  outbox:
    id: 1 --> causes the error
  database:
    schema: ${DATABASE_NAME}
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${KAFKA_URL}
  zookeeper:
    connection:
      string: ${ZOOKEEPER_URL}
server:
  port: ${APP_PORT}
spring:
  application:
    name: ${APP_NAME}
  jpa:
    generate-ddl: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

```
**pom.xml**
```
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-messaging</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-events</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-commands</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-jdbc-kafka</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
```
**Configuration**
```
import io.eventuate.tram.spring.events.common.TramEventsCommonAutoConfiguration;
import io.eventuate.tram.spring.events.publisher.TramEventsPublisherConfiguration;
import io.eventuate.tram.spring.jdbckafka.TramJdbcKafkaConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

@Configuration
@EnableAutoConfiguration
@Import({
        TramEventsPublisherConfiguration.class,
        TramEventsCommonAutoConfiguration.class,
        TramJdbcKafkaConfiguration.class
})
public class EventuateEventsConfiguration {

}

```
**docker-compose.yml**
```
version: '3'
name: EasyBuy
networks:
  app-tier:
    name: app-tier
services:
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    networks:
      - app-tier
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: bitnami/kafka:3.1.1
    networks:
      - app-tier
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
  eventuate-cdc:
    image: eventuateio/eventuate-cdc-service:0.13.0.RELEASE
    networks:
      - app-tier
    ports:
      - 8099:8080
    depends_on:
      - mysql
      - zookeeper
      - kafka
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_SERVICE_DRY_RUN: false
      USE_DB_ID: true
      # oneaccess
      EVENTUATE_CDC_READER_ONEACCESSREADER_TYPE: polling
      EVENTUATE_CDC_READER_ONEACCESSREADER_DATASOURCEURL: jdbc:mysql://mysql:3306/oneaccess_db?allowPublicKeyRetrieval=true&useSSL=false
      EVENTUATE_CDC_READER_ONEACCESSREADER_DATASOURCEUSERNAME: root
      EVENTUATE_CDC_READER_ONEACCESSREADER_DATASOURCEPASSWORD: password
      EVENTUATE_CDC_READER_ONEACCESSREADER_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
      EVENTUATE_CDC_READER_ONEACCESSREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/eventuatelocal
      EVENTUATE_CDC_READER_ONEACCESSREADER_OUTBOXID: 1
      EVENTUATE_CDC_PIPELINE_ONEACCESSPIPELINE_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_ONEACCESSPIPELINE_READER: oneaccessreader
      EVENTUATE_CDC_PIPELINE_ONEACCESSPIPELINE_EVENTUATEDATABASESCHEMA: oneaccess_db
.
.
.
```
